chore: remove tailwindcss & postcss redudant files
developersIndia/website pull request #129
Opened 2022-02-28 15:43 UTC by NiketanG

## Description

Tailwindcss was removed in favor of NextUI, [commit](https://github.com/developersIndia/website/commit/2e724c904908c689d58405a79f05536c079ffea7).

However, the imports are still present in [styles/globals.css](https://github.com/developersIndia/website/blob/master/src/styles/globals.css). 

Other redudant files like `tailwind.config.js` and `postcss.config.js` are also present. Which in turn cause the CI/CD to fail.

This PR removes those redudant files and deps. 

Fixes #126 

## Changes Include

- [x] Bug fix 🐛 

## How Has This Been Tested?

Tested on local system & CI/CD

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-02-28 16:04 UTC, Manav-SM submitted a review, later dismissed

2022-03-01 11:41 UTC, Jarmos-san requested changes

2022-03-01 11:41 UTC, Jarmos-san commented on README.md
> -- [TailwindCSS](https://tailwindcss.com)
Could you replace this like with the following instead:

```diff
- - [TailwindCSS](https://tailwindcss.com)
+ - [NextUI](https://nextui.org)
```

2022-03-01 11:43 UTC, Jarmos-san commented
PR looks good thanks for sharing & I'll merge it after you made the other subtle change.

Side note; The other PR you share earlier is **HUGE** & I'll review it over a weekend. I'll also need to setup the Netlify secret tokens which I don't have access to. So, I hope you understand & will be patient with me on that regards.

2022-03-01 15:25 UTC, NiketanG commented
> PR looks good thanks for sharing & I'll merge it after you made the other subtle change.
> 
> Side note; The other PR you share earlier is **HUGE** & I'll review it over a weekend. I'll also need to setup the Netlify secret tokens which I don't have access to. So, I hope you understand & will be patient with me on that regards.

Yes ofcourse man.

2022-03-01 16:16 UTC, Jarmos-san approved these changes

2022-03-01 16:20 UTC, merged